export const FILE_STORAGE_PORT = 'FILE_STORAGE_PORT';
export const FILE_REPOSITORY_PORT = 'FILE_REPOSITORY_PORT';
export const MESSAGING_PORT = 'MESSAGING_PORT';
export const ALLOWED_NUMBER = 'ALLOWED_NUMBER';
